POST https://graph.facebook.com/v18.0/103394759172111/messages
Content-Type: application/json
Authorization: Bearer EAADFKzVHjHwBO51G9UeBbf7lZBjJ3vduKnoK0WXfbSFv1mfEGO2az8kQqZBiH0yAeGNAdFT7x1ZBo1C7jGKwOZB6v3iIxZA0Qatqhb5w9UPKm7Q8tE9toZAQwqbhQuN3DNrymxGQZCpsx8efm90Nvhp4D9xWSCOm0BxA1vkssZBiS3J4L3lJLpNpbrSGLdbGKZA5SBL0w8ZCXXqtyBKuMabNoZD

{
    "messaging_product": "whatsapp",
    "recipient_type": "individual",
    "to": "5511953869941",
    "type": "text",
    "text": {
        "preview_url": false,
        "body": "Teste",
    }
}